site_name: Die Bond Docs
site_description: Describe what your site is about  # 设置文档网站的描述
site_url: 'https://example.com'  # 设置文档网站的 URL

theme:
  name: material
  language: en  # zh en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal

  features:
    #- navigation.instant
    #- navigation.sections         #启用了导航栏的章节功能。
    #- toc.integrate               #允许用户快速浏览文档的结构和内容。
    - navigation.top              #启用了返回页面顶部的功能
    - search.suggest              #启用了搜索建议功能
    - search.highlight            #启用了搜索结果高亮功能。
    - content.tabs.link           #启用了内容区域的选项卡链接功能
    - content.code.annotation     #启用了对代码块进行注释的功能
    - content.code.copy           #启用了复制代码块的功能。
    - navigation.tabs             #启用了导航栏的选项卡功能。

# Plugins
plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - offline

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
  - stylesheets/stylish.css


nav:  # 定义导航栏
  - Blog: 
    - Home: index.md  # 首页链接
    - 1.Software Init:
      - 1.1.Edit EPJ File: home/1.1.Edit_EPJ_File.md
      - 1.2.Operator Interface: home/1.2.Operator_Interface.md
      - 1.3.Client Needs: home/1.3.Client_Needs.md
    - 2.Alarms:
      - 2.1.with parameters: home/2.1.With_Parameters.md
      - 2.2.without parameters: home/2.2.Without_Parameters.md
    - 3.Variables:
      - 3.1.Status Variables: home/3.1.Status_Variables.md
      - 3.2.Data Variables: home/3.2.Data_Variables.md
      - 3.3.Equipment Constants: home/3.3.Equipment_Constants.md
    - 4.Events:
      - 4.1.Collection Events: home/4.1.Collection_Events.md
      - 4.2.Remote Commands: home/4.2.Remote_Commands.md
      - 4.3.Recipe Management: home/4.3.Recipe_Management.md
    - 5.Delivery Requirements:
      - 5.1.Host report request: home/5.1.Host_Report_Request.md
      - 5.2.Communications Manual: home/5.2.Communications_Manual.md
      - 5.3.Automatic machine test report: home/5.3.Automatic_Machine_Test_Report.md
    - 6.Software Tutorials:
      - 6.1.CIMConnect: home/6.1.CIMConnect.md
      - 6.2.EquipmentTest: home/6.2.EquipmentTest.md
      - 6.3.Remote Connection: home/6.3.Remote_Connection.md
  - AlarmList:
    - 01-Avaline_D: AlarmList/01-Avaline_D.md  #
    - 02-CCD: AlarmList/02-CCD.md  # 相机
    - 03-ClipBondCode: AlarmList/03-ClipBondCode.md  #
    - 04-ClipBondUl: AlarmList/04-ClipBondUl.md  #
    - 05-FlipBondCode: AlarmList/05-FlipBondCode.md  #
    - 06-FlipBondUl: AlarmList/06-FlipBondUl.md  #
    - 07-IntputContainer: AlarmList/07-IntputContainer.md  #
    - 08-IntputContainerUl: AlarmList/08-IntputContainerUl.md  #
    - 09-LoginUl: AlarmList/09-LoginUl.md  #
    - 10-Map: AlarmList/10-Map.md  #
    - 11-MaterialsDataDll: AlarmList/11-MaterialsDataDll.md  #
    - 12-Temperature: AlarmList/12-Temperature.md  #
    - 13-TinA: AlarmList/13-TinA.md  #
    - 14-TinAUI: AlarmList/14-TinAUI.md  #
    - 15-TinB: AlarmList/15-TinB.md  #
    - 16-TinBUI: AlarmList/16-TinBUI.md  #
    - 17-UITool: AlarmList/17-UITool.md  #
    - 18-WaferTableCode: AlarmList/18-WaferTableCode.md  #
    - 19-WaferTableUl: AlarmList/19-WaferTableUl.md  #
    - 20-CarryUI: AlarmList/20-CarryUI.md
  - SECS/GEM_Alarms:
    - 01-Avaline_D: SG_Alarms/01-Avaline_D.md  #
    - 02-CCD: SG_Alarms/02-CCD.md  # 相机
    - 03-ClipBondCode: SG_Alarms/03-ClipBondCode.md  #
    - 04-ClipBondUl: SG_Alarms/04-ClipBondUl.md  #
    - 05-FlipBondCode: SG_Alarms/05-FlipBondCode.md  #
    - 06-FlipBondUl: SG_Alarms/06-FlipBondUl.md  #
    - 07-IntputContainer: SG_Alarms/07-IntputContainer.md  #
    - 08-IntputContainerUl: SG_Alarms/08-IntputContainerUl.md  #
    - 09-LoginUl: SG_Alarms/09-LoginUl.md  #
    - 10-Map: SG_Alarms/10-Map.md  #
    - 11-MaterialsDataDll: SG_Alarms/11-MaterialsDataDll.md  #
    - 12-Temperature: SG_Alarms/12-Temperature.md  #
    - 13-TinA: SG_Alarms/13-TinA.md  #
    - 14-TinAUI: SG_Alarms/14-TinAUI.md  #
    - 15-TinB: SG_Alarms/15-TinB.md  #
    - 16-TinBUI: SG_Alarms/16-TinBUI.md  #
    - 17-UITool: SG_Alarms/17-UITool.md  #
    - 18-WaferTableCode: SG_Alarms/18-WaferTableCode.md  #
    - 19-WaferTableUl: SG_Alarms/19-WaferTableUl.md  #
    - All alarm: SG_Alarms/All alarm.md
    - README: SG_Alarms/README.md  #
  - SECS/GEM_Variables:
    - README: SG_Variables/README.md  #
  - SECS/GEM_Events:
    - README: SG_Events/README.md  #